###################
## Other Sensors ##
###################
command_line:
  - sensor:
      name: "Candy Washer Dryer"
      scan_interval: 60
      command_timeout: 30
      command: python3 ./pyscript/candy.py
      value_template: "{{ value_json }}"
      json_attributes:
        - StatoWiFi
        - StatoTD
        - Err
        - Pr
        - PrPh
        - RemTime
        - DryLev
        - DelVal
        - TotalTime
        - DoorState
        - CleanFilter
        - Refresh
        - Rapido
        - WaterTankFull
        - DryingManagerLevel

template:
  #####################
  ## Other Templates ##
  #####################
  #   Washer Dryer
  - sensor:
      - name: "Washer/Dryer - WiFi"
        icon: mdi:washing-machine
        state: >
          {% set WiFi = state_attr('sensor.candy_washer_dryer', 'StatoWiFi') | default(1) %}
          {% if WiFi == '0' %}On
          {% elif WiFi == '1' %}Off
          {% else %}{{ WiFi }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Error"
        icon: mdi:alert-circle
        state: >
          {% set Error = state_attr('sensor.candy_washer_dryer', 'Err') | default(255) %}
          {% if Error == '255' %}No Errors
          {% elif Error is number %}{{ Error }}
          {% else %}Off
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Status"
        icon: mdi:chart-pie
        state: >
          {% set Status = state_attr('sensor.candy_washer_dryer', 'StatoTD') %}
          {% if Status == "0" %}Stopped
          {% elif Status == "2" %}Running
          {% elif Status == "3" %}End
          {% elif Status == None %}Off
          {% else %}{{ Status }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Program"
        icon: mdi:progress-star
        state: >
          {% set Prog = state_attr('sensor.candy_washer_dryer', 'Pr') %}
          {% if Prog == "1" %}All In One
          {% elif Prog == "2" %}Dark and Colourful
          {% elif Prog == "3" %}White
          {% elif Prog == "4" %}Cotton
          {% elif Prog == "5" %}Shirts
          {% elif Prog == "6" %}Jeans
          {% elif Prog == "7" %}Synthetic
          {% elif Prog == "8" %}Waterproof Fabric
          {% elif Prog == "9" %}Sports
          {% elif Prog == "10" %}Duvets
          {% elif Prog == "11" %}Wool
          {% elif Prog == "12" %}Anti-allergy
          {% elif Prog == "13" %}XXL
          {% elif Prog == "14" %}Anti Odors
          {% elif Prog == None %}Off
          {% else %}{{ Prog }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Phase"
        icon: mdi:progress-question
        state: >
          {% set Phase = state_attr('sensor.candy_washer_dryer', 'PrPh') %} 
          {% if Phase == "0" %}Off
          {% elif Phase == "0" %}Idle
          {% elif Phase == "1" %}Running
          {% elif Phase == "2" %}Paused
          {% elif Phase == "3" %}Delayed start selection
          {% elif Phase == "4" %}Delayed start programmed
          {% elif Phase == "5" %}Error
          {% elif Phase == "6" %}Finished
          {% elif Phase == "7" %}Finished
          {% elif Phase == "8" %}Finished
          {% elif Phase == None %}Off
          {% else %}{{ Phase }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Dry Level"
        icon: mdi:thermometer-lines
        state: >
          {% set DryLevel = state_attr('sensor.candy_washer_dryer', 'DryLev') %}
          {% if DryLevel == None %}0
          {% elif DryLevel == "0" %}No Dry
          {% elif DryLevel == "1" %}Iron Dry
          {% elif DryLevel == "2" %}Hang Dry
          {% elif DryLevel == "3" %}Store Dry
          {% elif DryLevel == "4" %}Bone Dry
          {% else %}{{ DryLevel }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Dry Time"
        icon: mdi:timer
        unit_of_measurement: "mins"
        state: >
          {% set DryTime = state_attr('sensor.candy_washer_dryer', 'RemTime') %}
          {% if DryTime == None %}0
          {% else %}{{ DryTime | int }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Delay Time"
        icon: mdi:timer
        unit_of_measurement: "hours"
        state: >
          {% set DelT = state_attr('sensor.candy_washer_dryer', 'DelVal') %}
          {% if DelT == None %}0
          {% else %}{{ DelT | int }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Total Time"
        icon: mdi:timer
        state: >
          {% set TotalT = state_attr('sensor.candy_washer_dryer', 'TotalTime') %}
          {% if TotalT == None %}0
          {% else %}{{ TotalT }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Max Delay"
        icon: mdi:timer
        state: >
          {% set Status = states('sensor.washer_dryer_wifi') %}
          {% set Delay = states('sensor.washer_dryer_delay_time') | int(default=0) * 60 %}
          {% set DelayMax = states('sensor.washer_dryer_max_delay') | int(default=0) %}
          {% set Total = states('sensor.washer_dryer_total_time') | int %}
          {% if Total == 0 %}0
          {% elif Status == 'Off' %}{{ DelayMax }}
          {% elif DelayMax >= Delay %}{{ DelayMax }}
          {% else %}{{ Delay }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Door Status"
        icon: mdi:door
        state: >
          {% set DoorState = state_attr('sensor.candy_washer_dryer', 'DoorState') %}
          {% if DoorState == None %}Off
          {% elif DoorState == "0" %}Door Open
          {% elif DoorState == "1" %}Door Close
          {% else %}{{ DoorState }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Clean Filter"
        icon: mdi:door
        state: >
          {% set CleanFilter = state_attr('sensor.candy_washer_dryer', 'CleanFilter') %}
          {% if CleanFilter == None %}Off
          {% elif CleanFilter == "0" %}Clean
          {% elif CleanFilter == "1" %}Needs Cleaning
          {% else %}{{ CleanFilter }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Water Tank"
        icon: mdi:door
        state: >
          {% set WaterTankFull = state_attr('sensor.candy_washer_dryer', 'WaterTankFull') %}
          {% if WaterTankFull == None %}Off
          {% elif WaterTankFull == "0" %}Empty
          {% elif WaterTankFull == "1" %}Full
          {% else %}{{ WaterTankFull }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Rapid Cycle"
        icon: mdi:door
        state: >
          {% set Rapid = state_attr('sensor.candy_washer_dryer', 'Rapido') %}
          {% if Rapid == None %}Off
          {% elif Rapid == "0" %}Full cycle
          {% elif Rapid == "1" %}Rapid Cycle
          {% else %}{{ Rapid }}
          {% endif %}
  - sensor:
      - name: "Washer/Dryer - Refresh Cycle"
        icon: mdi:door
        state: >
          {% set Refresh = state_attr('sensor.candy_washer_dryer', 'Refresh') %}
          {% if Refresh == None %}Off
          {% elif Refresh == "0" %}Full cycle
          {% elif Refresh == "1" %}Refresh Cycle
          {% else %}{{ Refresh }}
          {% endif %}
